title: Elcosas's Blog
description: "Elcosas's personal blog"
author:
  name: "Cole Saldanha"
  url: "https://elcosas.github.io/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 5
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Elcosas"
year : "2023"
